SIG.SIGCMS/Areas/Admin/Controllers/LogController.cs
using System;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SIG.Infrastructure.Configs;
using SIG.Model.Admin.ViewModel;
using SIG.Model.Admin.ViewModel.Log;
using SIG.Services.Log;

namespace SIG.SIGCMS.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LogController : BaseController
    {
        private readonly ILogServices _logServices;
        private readonly IMapper _mapper;

        public LogController(ILogServices logServices, IMapper mapper)
        {
            _logServices = logServices;
            _mapper = mapper;

        }



        public IActionResult Index(int? page, DateTime? startDate, DateTime? expireDate, string level)
        {
            var logSearchVM = new LogSearchVM()
            {
                StartDate = startDate,
                ExpireDate = expireDate,
                Level = level,

                PageIndex = (page ?? 1),
                PageSize = SettingsManager.Log.PageSize
            };
            int totalCount;
            logSearchVM.Logs = _logServices.SearchLogs(logSearchVM.PageIndex - 1, logSearchVM.PageSize, startDate,
                expireDate, level, out totalCount);
            logSearchVM.TotalUserCount = totalCount;

            //logSearchVM.Logs = _mapper.Map<IEnumerable<LogVM>>(logs);

            //var logsAsIPagedList =  new StaticPagedList<LogVM>(logSearchVM.Logs, logSearchVM.PageIndex, logSearchVM.PageSize, logSearchVM.TotalUserCount);
            //ViewBag.OnePageOfLogs = logsAsIPagedList;

            return View(logSearchVM);

        }



        [HttpPost]
        public JsonResult Delete(string id)
        {
            try
            {
                if (id == "all")
                {
                    _logServices.RemoveAll();
                    
                    AR.SetSuccess("已清空所有日志");
                    return Json(AR);

                }
                else
                {

                    int logId;
                    Int32.TryParse(id, out logId);
                    _logServices.Delete(logId);

                    AR.SetSuccess("已成功删除日志");
                    return Json(AR);

                }
        }
            catch (Exception ex)
            {
                AR.Setfailure(ex.Message);
                return Json(AR);
    }

}
    }
}

SIG.SIGCMS/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SIG.Data.Entity.Identity;
using SIG.Data.Enums;
using SIG.Infrastructure.Configs;
using SIG.Infrastructure.Helper;
using SIG.Model.Admin.InputModel.Menus;
using SIG.Model.Admin.ViewModel;
using SIG.Model.Admin.ViewModel.Menus;
using SIG.Resources.Admin;
using SIG.Services;
using SIG.Services.Menus;

namespace SIG.SIGCMS.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MenuController : BaseController
    {
        private readonly IMenuCategoryServices _menuCategoryService;
        private readonly IMenuServices _menuService;
        private readonly IViewRenderService _viewRenderService;
        private readonly IMapper _mapper;

        public MenuController(IMenuServices menuService, IMenuCategoryServices menuCategoryService, IViewRenderService viewRenderService, IMapper mapper)
        {
            _menuService = menuService;
            _menuCategoryService = menuCategoryService;
            _viewRenderService = viewRenderService;
            _mapper = mapper;
        }

        //
        // GET: /Admin/Menu/ 
        public ActionResult Index()
        {
            var menuCategory = _menuCategoryService.GetById(SettingsManager.Menu.BackMenuCId);
            //  var vm = _mapper.Map<MenuCategoryVM>(menuCategory);      
            return View(menuCategory);
        }

        /// <summary>
        /// 获取单组菜单
        /// </summary>
        /// <param name="categoryId"></param>
        /// <returns></returns>
        //[AllowAnonymous]
        public IActionResult GetMenus(int categoryId)
        {
            //不支持控制器视图查看
            return ViewComponent("MenuList", new { categoryId = categoryId });
        }





        [HttpGet]
        public ActionResult CreateMenu(int categoryId, int parentId)
        {
            var vMenu = new Menu();
            MenuIM newDto = _mapper.Map<MenuIM>(vMenu);

            newDto.CategoryId = (int)categoryId;
            newDto.ParentId = parentId;
            return PartialView("_MenuCreate", newDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreateMenu(MenuIM menu)
        {

            if (ModelState.IsValid)
            {
                var vMenu = _mapper.Map<Menu>(menu);

                var parentMenu = _menuService.GetById(vMenu.ParentId.Value);
                vMenu.LayoutLevel = parentMenu.LayoutLevel + 1;
                vMenu.CreatedBy = Site.CurrentUserName;
                vMenu.CreatedDate = DateTime.Now;



                //自动添加通用操作
                if (vMenu.CategoryId == SettingsManager.Menu.BackMenuCId && vMenu.MenuType == MenuType.PAGE)
                {
                    vMenu.ChildMenus.Add(new Menu
                    {
                        Title = "添加",
                        Controller = vMenu.Controller,
                        Action = "Add",
                        Area = vMenu.Area,
                        MenuType = MenuType.ACTION,
                        CategoryId = vMenu.CategoryId,
                        LayoutLevel = vMenu.LayoutLevel + 1,

                        CreatedBy = Site.CurrentUserName,
                        CreatedDate = DateTime.Now,
                    });


                    vMenu.ChildMenus.Add(new Menu
                    {
                        Title = "编辑",
                        Controller = vMenu.Controller,
                        Action = "Edit",
                        Area = vMenu.Area,
                        MenuType = MenuType.ACTION,
                        CategoryId = vMenu.CategoryId,
                        LayoutLevel = vMenu.LayoutLevel + 1,

                        CreatedBy = Site.CurrentUserName,
                        CreatedDate = DateTime.Now,
                    });

                    vMenu.ChildMenus.Add(new Menu
                    {
                        Title = "显示/隐藏",
                        Controller = vMenu.Controller,
                        Action = "IsActive",
                        Area = vMenu.Area,
                        MenuType = MenuType.ACTION,
                        CategoryId = vMenu.CategoryId,
                        LayoutLevel = vMenu.LayoutLevel + 1,

                        CreatedBy = Site.CurrentUserName,
                        CreatedDate = DateTime.Now,
                    });

                    vMenu.ChildMenus.Add(new Menu
                    {
                        Title = "删除",
                        Controller = vMenu.Controller,
                        Action = "Delete",
                        Area = vMenu.Area,
                        MenuType = MenuType.ACTION,
                        CategoryId = vMenu.CategoryId,
                        LayoutLevel = vMenu.LayoutLevel + 1,

                        CreatedBy = Site.CurrentUserName,
                        CreatedDate = DateTime.Now,
                    });

                    vMenu.ChildMenus.Add(new Menu
                    {
                        Title = "分页设置",
                        Controller = vMenu.Controller,
                        Action = "PageSizeSet",
                        Area = vMenu.Area,
                        MenuType = MenuType.ACTION,
                        CategoryId = vMenu.CategoryId,
                        LayoutLevel = vMenu.LayoutLevel + 1,
                        // ParentId = result,
                        CreatedBy = Site.CurrentUserName,
                        CreatedDate = DateTime.Now,
                    });

                }

                var result = _menuService.Create(vMenu);
                //_menuService.CreateAndSort(vMenu);           
                _menuService.ResetSort(menu.CategoryId);

                var menus = _menuService.GetLevelMenusByCategoryId(vMenu.CategoryId);
                AR.Id = menu.CategoryId;
                //AR.Data = ViewComponent("MenuList", new { categoryId = menu.CategoryId });  //await _viewRenderService.RenderToStringAsync("Admin/Menu/_MenuList", menus);

                AR.SetSuccess("已成功新增菜单");
                return Json(AR);
            }

            AR.Setfailure("编辑菜单失败");
            return Json(AR);
            //   return RedirectToAction("Index");

        }


        [HttpGet]
        [AllowAnonymous]
        public ActionResult EditMenu(int id)
        {
            Menu vMenu = _menuService.GetById(id);
            MenuIM dto = _mapper.Map<MenuIM>(vMenu);
            return PartialView("_MenuEdit", dto);

        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult EditMenu(MenuIM menu)
        {

            if (ModelState.IsValid)
            {
                Menu vMenu = _mapper.Map<Menu>(menu);

                Menu orgMenu = _menuService.GetById(vMenu.Id);
                orgMenu.Title = vMenu.Title;
                orgMenu.MenuType = vMenu.MenuType;
                orgMenu.Active = vMenu.Active;
                orgMenu.Action = vMenu.Action;
                orgMenu.Area = vMenu.Area;
                orgMenu.CategoryId = vMenu.CategoryId;
                orgMenu.Controller = vMenu.Controller;
                orgMenu.Iconfont = vMenu.Iconfont;
                orgMenu.ParentId = vMenu.ParentId;
                orgMenu.Url = vMenu.Url;
                orgMenu.UpdatedBy = Site.CurrentUserName;
                orgMenu.UpdatedDate = DateTime.Now;

                _menuService.Update(orgMenu);

                // _menuService.ResetSort(orgMenu.CategoryId);

              //  var menus = _menuService.GetLevelMenusByCategoryId(vMenu.CategoryId);
                AR.Id = vMenu.CategoryId;
                //// using a Model
                //string html = view.Render("Emails/Test", new Product("Apple"));

                //// using a Dictionary<string, object>
                //var viewData = new Dictionary<string, object>();
                //viewData["Name"] = "123456";

                //string html = view.Render("Emails/Test", viewData);

                //AR.Data = await _viewRenderService.RenderToStringAsync("_MenuList", menus);

                AR.SetSuccess("已成功保存菜单");
                return Json(AR);

            }

            AR.Setfailure("编辑菜单失败");
            return Json(AR);



        }



        // POST: Admin/User/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {

            Menu vMenu = _menuService.GetByIdWithChilds(id);

            if (vMenu != null)
            {

                int cid = vMenu.CategoryId;
                if (SettingsManager.Menu.BackMenuCId == cid)
                {
                    if (User.Identity.Name != SettingsManager.User.Founder)
                    {
                        AR.SetWarning(string.Format(Messages.NotFounderCanNotDelete, EntityNames.Menu));
                        return Json(AR);
                    }

                }

                // var childMenuCount = _menuService.GetMenuCount(id);
                if (vMenu.ChildMenus.Count > 1)
                {
                    AR.Setfailure(string.Format(Messages.AlertDeleteFailureHasChild, EntityNames.Menu));
                    return Json(AR);
                }

                //  vMenu.Roles.Clear();
                _menuService.Delete(vMenu);
                //  _menuService.DeleteMenuWithRoles(id);
                _menuService.ResetSort(vMenu.CategoryId);

                //var menus = await _menuService.GetMenus(cid);
                //return PartialView("_MenuList", menus);
                AR.SetSuccess(string.Format(Messages.AlertDeleteSuccess, EntityNames.Menu));
                return Json(AR);
            }
            AR.Setfailure(string.Format(Messages.AlertDeleteFailure, EntityNames.Menu));
            return Json(AR);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]

SIG.SIGCMS/Areas/Admin/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SIG.Data.Entity.Identity;
using SIG.Infrastructure.Configs;
using SIG.Model.Admin.InputModel.Identity;
using SIG.Model.Admin.ViewModel;
using SIG.Resources.Admin;
using SIG.Services.Identity;
using SIG.Services.Menus;
using TZGCMS.Model.Admin.ViewModel.Identity;

namespace SIG.SIGCMS.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : BaseController
    {
        private readonly IRoleServices _roleServices;
        //private readonly IMenuServices _menuServices;

        private readonly IMapper _mapper;
        public RoleController(IRoleServices roleServices, IMapper mapper)
        {
            _roleServices = roleServices;
            //_menuServices = menuServices;
            _mapper = mapper;
        }

        // GET: Role
        public IActionResult Index()
        {
            var roles = _roleServices.GetAll().Where(r => r.Id != SettingsManager.Role.Founder);
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_List", roles);
            }
            return View(roles);
        }

        //[AllowAnonymous]
        //public PartialViewResult List()
        //{
        //    var roles = _roleServices.GetAll().Where(r => r.Id != SettingsManager.Role.Founder);
        //    return PartialView("_List", roles);
        //}



        [HttpGet]
        // GET: Roles/Create
        public ActionResult SetRoleMenus(int id)
        {
            var role = _roleServices.GetById(id);
          //  var menus = _menuServices.GetMenusByCategoryId(SettingsManager.Menu.BackMenuCId);
          //  int[] menuIds = role.RoleMenus?.Select(m => m.MenuId).ToArray();

            SetRoleMenusVM vm = new SetRoleMenusVM
            {
                RoleId = id,
               // Menus = menus,
               // MenuIds = menuIds
            };
            return PartialView("_SetRoleMenus",vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetRoleMenus(int RoleId, int[] menuId)
        {

            if (RoleId > 0)
            {
                _roleServices.SetRoleMenus(RoleId, menuId);
                return Json(AR);
            }
            AR.Setfailure("编辑角色权限失败");
            return Json(AR);
        }

        [HttpGet]
        public ActionResult EditRole(int? id)
        {
            var role = (id > 0) ? _roleServices.GetById(id.Value) : new Role();
            var vm = _mapper.Map<RoleIM>(role);
            return PartialView("_EditRole", vm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditRole(RoleIM role)
        {

            if (ModelState.IsValid)
            {
                if (role.Id > 0)
                {
                    Role vRole = _roleServices.GetById(role.Id);
                    if (!vRole.IsSys)
                    {
                        vRole.RoleName = role.RoleName;
                        vRole.Description = role.Description;
                        _roleServices.Update(vRole);
                    }
                    else
                    {
                        //  return new HttpStatusCodeResult(500, "系统角色不可编辑");
                        AR.SetWarning("系统角色不可编辑");
                        return Json(AR);
                    }

                }
                else
                {
                    var vm = _mapper.Map<Role>(role);
                    _roleServices.Create(vm);
                }
             
                AR.SetSuccess(String.Format(Messages.AlertCreateSuccess, EntityNames.Role));
                return Json(AR);
            }
            //return new HttpStatusCodeResult(500, "编辑角色失败");

            AR.Setfailure("编辑角色失败");
            return Json(AR);
        }



        // POST: Roles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {

            var role = _roleServices.GetById(id);
            if (role.IsSys)
            {
                AR.SetWarning("系统角色，不可以删除！");
                return Json(AR);
            }
            _roleServices.Delete(role);
            return Json(AR);

        }

    }
}

SIG.SIGCMS/Controllers/API/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace SIG.SIGCMS.Controllers.API
{
    [Produces("application/json")]
    [Route("api/User")]
    public class UserController : Controller
    {
        // GET: api/User
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/User/5
        [HttpGet("{id}", Name = "Get")]
        public string Get(int id)
        {
            return "value";
        }
        
        // POST: api/User
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }
        
        // PUT: api/User/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }
        
        // DELETE: api/ApiWithActions/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

SIG.SIGCMS/Areas/Admin/Views/Shared/_Layout.cshtml
@using SIG.Infrastructure.Configs
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/icons/fontawesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/plugins/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/admin/css/main.min.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    @RenderSection("header", required: false)
</head>
<body>



<div id="wrapper">
    
    @*<div id="sidebar-nav" class="leftcol">
        <aside>
            <nav id="menu">
                <h3>导航</h3>
                <ul class="list-unstyled mainmenu">
                    <li class="liitem nav-open">
                        <a href="Default.html" class="active">
                            <i class="fa fa-dashboard"></i> 控制面板
                            <div class="arrow-left"></div>
                        </a>
                    </li>

                    <li class="liitem down-nav">
                        <a href="#"><i class="fa fa-table"></i> 表格 <span class="badge">2</span></a>
                        <ul class="list-unstyled submenu">
                            <li>
                                <a href="TableBasic.html">
                                    <i class="fa fa-angle-double-right"></i> 表格一
                                </a>
                            </li>
                            <li><a href="/BBI-Admin/Articles/NewsCategories.html"><i class="fa fa-angle-double-right"></i> 表格二</a></li>
                        </ul>
                    </li>
                    <li class="liitem down-nav">
                        <a href="#"><i class="fa fa-edit"></i> 表单 <span class="badge">2</span></a>
                        <ul class="list-unstyled submenu">
                            <li><a href="FormBasic.html"><i class="fa fa-angle-double-right"></i> 基本表单</a></li>
                            <li><a href="/BBI-Admin/Ad/ManagePositions.aspx"><i class="fa fa-angle-double-right"></i> 带验证表单</a></li>
                        </ul>
                    </li>
                    <li class="liitem"><a href="/BBI-Admin/Pages/ManagePages.aspx"><i class="fa fa-paste"></i> 内容片段</a></li>
                    <li class="liitem down-nav">
                        <a href="#"><i class="fa fa-link"></i> 链接管理 <span class="badge">2</span></a>
                        <ul class="list-unstyled submenu">
                            <li><a href="/BBI-Admin/Links/ManageLinks.aspx"><i class="fa fa-angle-double-right"></i> 链接列表</a></li>
                            <li><a href="/BBI-Admin/Links/ManageCategories.aspx"><i class="fa fa-angle-double-right"></i> 链接分类</a></li>
                        </ul>
                    </li>

                    <li class="liitem down-nav">
                        <a href="#"><i class="fa fa-shield"></i> 其它页面 <span class="badge">2</span></a>
                        <ul class="list-unstyled submenu">
                            <li><a href="../Login.html"><i class="fa fa-angle-double-right"></i> 登录页</a></li>
                            <li><a href="../Register.html"><i class="fa fa-angle-double-right"></i> 注册页</a></li>
                        </ul>
                    </li>
                    <li class="liitem down-nav">
                        <a href="#"><i class="fa fa-cog"></i> 常规设置 <span class="badge">4</span></a>
                        <ul class="submenu">
                            <li><a href="/bbi-admin/Common/SiteInfo.aspx"><i class="fa fa-home"></i> 站点信息</a></li>
                            <li><a href="/bbi-admin/Common/CompanyInfo.aspx"><i class="fa fa-info-circle"></i> 企业信息</a></li>
                            <li><a href="/bbi-admin/Common/Social.aspx"><i class="fa fa-twitter"></i> 社交资料</a></li>
                            <li class="hide"><a href="/bbi-admin/Common/MailSettings.aspx"><i class="fa fa-envelope-o"></i> 邮箱服务设置</a></li>
                        </ul>
                    </li>
                    <li class="liitem down-nav">
                        <a href="#"><i class="fa fa-cog"></i> 系统 <span class="badge">4</span></a>
                        <ul class="submenu">
                            <li><a asp-controller="Menu" asp-action="Index"><i class="fa fa-user"></i> 后台菜单</a></li>
                            <li><a asp-controller="Log" asp-action="Index"><i class="fa fa-bug"></i> 日志</a></li>
                            <li><a asp-controller="User" asp-action="Index"><i class="fa fa-user"></i> 用户</a></li>
                            <li><a asp-controller="Role" asp-action="Index"><i class="fa fa-key"></i> 角色</a></li>

                            <li class="hide"><a href="/bbi-admin/Common/MailSettings.aspx"><i class="fa fa-envelope-o"></i> 邮箱服务设置</a></li>
                        </ul>
                    </li>
                </ul>

            </nav>
            <div class="closemenu">
                <a href="#"><i class="fa fa-chevron-circle-left"></i></a>
            </div>
        </aside>
    </div>*@
    @await Component.InvokeAsync("LeftNav", new { categoryId = SettingsManager.Menu.BackMenuCId, viewContext = ViewContext })
    <div id="rightcol" class="rightcol">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">

            <a class="navbar-brand" href="#">
                <img src="../Content/Admin/img/logo.png" height="30" alt="" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                </ul>
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-item active"><a href="/" class="nav-link"><i class="fa fa-home"></i> 返回首页 <span class="sr-only">(current)</span></a></li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            你好，Admin
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">个人资料</a>
                            <a class="dropdown-item" href="#">修改密码</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">我的订单</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Logout" asp-route-area=""><i class="fa fa-sign-out"></i> 退出系统</a>
                    </li>
                </ul>
            </div>
        </nav>


        @await Component.InvokeAsync("Crumbs", new {viewContext = ViewContext})

        @*<div class="toolbar">
                <a href="#" class="showmenu"><i class="fa fa-bars"></i></a>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-home fa-fw"></i> 控制面板</a></li>
                    <li><a href="#">Library</a></li>
                    <li class="active">Data</li>
                </ol>
            </div>*@
        <div class="main-content">
            @RenderBody()
        </div>

        <footer id="pagefooter" class="page-footer">
            Copyright &copy; 2012 <a id="hlSiteInfo" href="http://heiniaozhi.cn">黑鸟志</a> All Rights
            Reserved
        </footer>

    </div>
</div>
    

<script src="~/admin/js/jquery-3.2.1.min.js"></script>
<script src="~/js/lib/popper/popper.min.js"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/plugins/bootbox/bootbox.min.js"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>
<script src="~/admin/js/App.js"></script>
    
@RenderSection("footer", required: false)
</body>
</html>